name: Main Test

on:
  pull_request:
    branches: ["master"]
    paths:
      - "Testing/**"
  push:
    branches: ["Testing"]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Run test
        run: mvn test
